# Generated by Django 3.2.5 on 2021-07-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pythontip',
            name='timestamp',
            field=models.CharField(max_length=20),
        ),
    ]
